# You can use this file to create a conda environment for the genome-annotation pipeline:
#   conda env create -f environment.yml
name: LaMeta-1.0
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
 - parallel
 - bbmap=38.22
 - megahit=1.1.3
 - spades=3.13
 - samtools=1.9
 - metabat2=2.12.1
 - maxbin2=2.2.6
 - prodigal=2.6.3
 - hmmer=3.2.1
 - r-base=3.5.1
 - gtdbtk=0.1.6
 - checkm-genome=1.0.13
 - biopython
 - multiqc=1.6
